import {
  Globe,
  Smartphone,
  Brain,
  Cloud,
  Palette,
  ShoppingCart,
  Award,
  Briefcase,
  Smile,
  Headphones,
  Search,
  PenTool,
  Code,
  CheckCircle,
  Rocket,
  Linkedin,
  Twitter,
  Instagram,
  Github,
  Mail,
  Phone,
  MessageCircle,
  ArrowRight,
  ChevronDown,
  Menu,
  X,
  Zap,
  Star,
  MapPin,
  Send,
  Shield,
  Clock,
  Check,
  Info,
  Sparkles,
  Box,
  Handshake,
  Film,
  ChevronRight,
  ChevronLeft,
  ExternalLink
} from "lucide-react";

const icons: Record<string, React.ReactNode> = {
  globe: <Globe size={20} />,
  smartphone: <Smartphone size={20} />,
  brain: <Brain size={20} />,
  cloud: <Cloud size={20} />,
  palette: <Palette size={20} />,
  shoppingCart: <ShoppingCart size={20} />,
  award: <Award size={20} />,
  briefcase: <Briefcase size={20} />,
  smile: <Smile size={20} />,
  headphones: <Headphones size={20} />,
  search: <Search size={20} />,
  pen: <PenTool size={20} />,
  code: <Code size={20} />,
  checkCircle: <CheckCircle size={20} />,
  rocket: <Rocket size={20} />,
  linkedin: <Linkedin size={20} />,
  twitter: <Twitter size={20} />,
  instagram: <Instagram size={20} />,
  github: <Github size={20} />,
  mail: <Mail size={20} />,
  phone: <Phone size={20} />,
  whatsapp: <MessageCircle size={20} />,
  arrow: <ArrowRight size={20} />,
  chev: <ChevronDown size={20} />,
  chevRight: <ChevronRight size={20} />,
  chevLeft: <ChevronLeft size={20} />,
  menu: <Menu size={20} />,
  close: <X size={20} />,
  zap: <Zap size={20} />,
  star: <Star size={20} />,
  mapPin: <MapPin size={20} />,
  send: <Send size={20} />,
  shield: <Shield size={20} />,
  clock: <Clock size={20} />,
  check: <Check size={20} />,
  info: <Info size={20} />,
  spark: <Sparkles size={20} />,
  cube: <Box size={20} />,
  handshake: <Handshake size={20} />,
  film: <Film size={20} />,
  externalLink: <ExternalLink size={20} />,
  bolt: <Zap size={20} />,
  chat: <MessageCircle size={20} />,
};

export function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const el = icons[name];
  if (!el) return null;
  // Clone the element with custom size if different from default
  if (size !== 20) {
    const IconComponents: Record<string, React.ElementType> = {
      globe: Globe, smartphone: Smartphone, brain: Brain, cloud: Cloud,
      palette: Palette, shoppingCart: ShoppingCart, award: Award,
      briefcase: Briefcase, smile: Smile, headphones: Headphones,
      search: Search, pen: PenTool, code: Code, checkCircle: CheckCircle,
      rocket: Rocket, mail: Mail, phone: Phone, whatsapp: MessageCircle,
      arrow: ArrowRight, chev: ChevronDown, chevRight: ChevronRight,
      chevLeft: ChevronLeft, menu: Menu, close: X, zap: Zap, star: Star,
      mapPin: MapPin, send: Send, shield: Shield, clock: Clock, check: Check,
      info: Info, spark: Sparkles, cube: Box, handshake: Handshake,
      film: Film, externalLink: ExternalLink, bolt: Zap, chat: MessageCircle,
      linkedin: Linkedin, twitter: Twitter, instagram: Instagram, github: Github,
    };
    const Comp = IconComponents[name];
    if (Comp) return <Comp size={size} />;
  }
  return <>{el}</>;
}
